# Generated by Django 5.1.1 on 2024-09-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_booking_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userroom',
            name='end_date',
            field=models.DateTimeField(verbose_name='Дата конца бронирования'),
        ),
        migrations.AlterField(
            model_name='userroom',
            name='start_date',
            field=models.DateTimeField(verbose_name='Дата начала бронирования'),
        ),
    ]
